### ISSUE TITLE
the code of the callback function seems is missing

### ISSUE THREAD

**Issue by wmliang** [casys-kaist/segfuzz#1]
the code of the callback function, which is used by the compiler pass, is missing
the name should be `__ssb_[tso|pso]_`
but i didn't find it in this project
please update me if i misunderstand it

btw, thanks for sharing the source

**Comment by threeearcat** [comment]
Those callback functions are implemented in our Linux repo.
We used our internal Linux repo during the project, and now I'm working on publishing the Linux repo.
Thank you for your understanding, and I will finish it soon.

**Comment by dengnan0819** [comment]
Hi，is this finished？

> 这些回调函数在我们的 Linux 存储库中实现。 我们在项目期间使用了内部 Linux 存储库，现在我正在致力于发布 Linux 存储库。 谢谢您的理解，我会尽快完成。



> Those callback functions are implemented in our Linux repo. We used our internal Linux repo during the project, and now I'm working on publishing the Linux repo. Thank you for your understanding, and I will finish it soon.

Hi，is this finished？I am very interested in how to run segfuzz！
